---
- name: Customize Parent Playbooks
  hosts: localhost

  tasks:
  - name: Set FQDN
    ansible.builtin.shell: uname -n | cut -c 9-13
    register : fqdn

  - name: Set IP for HANA1
    ansible.builtin.shell: host hana-{{ fqdn.stdout }}1 | cut -f 4 -d " "
    register : hana1ip

  - name: Set IP for HANA2
    ansible.builtin.shell: host hana-{{ fqdn.stdout }}2 | cut -f 4 -d " "
    register : hana2ip

  - name: Prepare hanas in group_vars
    ansible.builtin.template:
      src: /root/hanaworkshop-2024/temp/hanas
      dest: /root/hanaworkshop-2024/group_vars/hanas
      mode: '0644'

  - name: Prepare s4hana deploy playbook
    ansible.builtin.template:
      src: /root/hanaworkshop-2024/temp/05_s4hana_deploy.yml
      dest: /root/hanaworkshop-2024/s4-ap/05_s4hana_deploy.yml
      mode: '0644'

  - name: Delete DEPRECATION WARNING
    ansible.builtin.lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^#deprecation_warnings = True'
      line: 'deprecation_warnings = False'
    become: true

- name: Transfer and execute a script.
  hosts: sap

  tasks:
    - name: Transfer the script
      ansible.builtin.copy:
        src: /root/hanaworkshop-2024/pkg_fix.sh
        dest: /home/cloud-user
        mode: '0777'

    - name: Execute the script
      ansible.builtin.command: sh /home/cloud-user/pkg_fix.sh
