---
- name: RFC Connection to SAP
  hosts: localhost
  become: yes
  collections:
    - community.sap_operations

  vars:
    suser_id: 'S0020405660'
    suser_password: 'RW!6AmRMTwZ!7H5'
    sap_nwrfc_sdk: nwrfc750P_11-70002752.zip
    reuse_connection:
      ashost: s4hana-rfng9
      sysid: RHE
      sysnr: "00"
      client: "000"
      user: "SAP*"
      passwd: R3dh4t123!
      lang: EN

  tasks:

  - name: Run SAP RFC - STFC_CONNECTION
    vars:
      pyrfc_first_run: yes
      target_function: STFC_CONNECTION
      target_parameters:
        REQUTEXT: 'Hello SAP!'
      target_connection: "{{ reuse_connection }}"
    ansible.builtin.include_role:
      name: community.sap_operations.sap_pyrfc
      #    register: sap_rfc_output1

  - name: DEBUG - Output of STFC_CONNECTION
    debug:
      msg: "{{ sap_rfc_output }}"

  - name: Run SAP RFC - STFC_STRUCTURE
    vars:
      pyrfc_first_run: no
      target_function: STFC_STRUCTURE
      target_parameters:
        IMPORTSTRUCT:
          RFCINT1: 128
        RFCTABLE:
          - RFCDATA1: test
      target_connection: "{{ reuse_connection }}"
    ansible.builtin.include_role:
      name: community.sap_operations.sap_pyrfc
      #register: sap_rfc_output2

  - name: DEBUG - Output of STFC_STRUCTURE
    debug:
      msg: "{{ sap_rfc_output }}"
      