---
- name: Transfer and execute a script.
  hosts: hanas

  tasks:
  - name: Set node information
    set_fact:
      _nodes: "{{ _nodes | default([]) + [{'hostname': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_eth0.ipv4.address}] }}"
    run_once: yes
    with_items: "{{ ansible_play_hosts }}"
    when:
      - hostvars[item].ansible_eth0 is defined

  - name: Create additional hosts entries to /tmp/hosts.txt
    become: yes
    template:
      src: hosts.j2
      dest: /tmp/hosts.txt
      owner: root
      group: root
      mode: 0644
      force: yes

  - name: Copy hosts.txt to local
    fetch:
      src: /tmp/hosts.txt
      dest: /tmp/hosts.txt
      flat: yes

  - name: Insert to /etc/hosts on HANA node
    blockinfile: 
      path: /etc/hosts
      insertafter: EOF
      marker: "# {mark} ANSIBLE Fish-shell basic setup."
      backup: yes
      block: "{{ item }}"
    with_file:
      - /tmp/hosts.txt
