---
- name: Install SAP AP server
  hosts: s4hanas

  vars:
    sap_s4hana_deployment_swpm_path: "/software/S4HANA_installation"
    sap_s4hana_deployment_swpm_sar_file_name: "SWPM20SP04_6-80003424.SAR"
    sap_s4hana_deployment_sapcar_path: "/software/SAPCAR"
    sap_s4hana_deployment_sapcar_file_name: "SAPCAR_1311-80000935.EXE"
    sap_s4hana_deployment_product_id: "NW_ABAP_OneHost:S4HANA1909.CORE.HDB.ABAP"

    sap_s4hana_deployment_master_password: "R3dh4t123!"
    sap_s4hana_deployment_hana_systemdb_password: "R3dh4t123!"
    sap_s4hana_deployment_db_schema_abap_password: "R3dh4t123!"
    sap_s4hana_deployment_sid: "RHE"
    sap_s4hana_deployment_db_host: "hana-xxxxx1"
    sap_s4hana_deployment_db_sid: "RHE"
    sap_s4hana_deployment_hana_instance_nr: "01"
    sap_s4hana_deployment_hana_system_password: "R3dh4t123!"
    sap_s4hana_deployment_parallel_jobs_nr: "30"
    sap_s4hana_deployment_db_sidadm_password: "R3dh4t123!"
    sap_s4hana_deployment_igs_path: "/software/S4HANA_installation"
    sap_s4hana_deployment_igs_file_name: "igsexe_9-80003187.sar"
    sap_s4hana_deployment_igs_helper_path: "/software/S4HANA_installation"
    sap_s4hana_deployment_igs_helper_file_name: "igshelper_17-10010245.sar"
    sap_s4hana_deployment_kernel_dependent_path: "/software/S4HANA_installation"
    sap_s4hana_deployment_kernel_dependent_file_name: "SAPEXEDB_201-80003385.SAR"
    sap_s4hana_deployment_kernel_independent_path: "/software/S4HANA_installation"
    sap_s4hana_deployment_kernel_independent_file_name: "SAPEXE_201-80003386.SAR"
    sap_s4hana_deployment_software_path: "/software/S4HANA_installation"
    sap_s4hana_deployment_fqdn: "example.com"

  roles:
    - redhat_sap.sap_s4hana_deployment
